name:                icfpc2021
version:             0.1.0.0
github:              "nobsun/icfpc2021"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2021 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/icfpc2021#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- filepath
- aeson

library:
  source-dirs: src
  dependencies:
  - utf8-string
  - unicode-show
  - fgl
  - containers
  - transformers
  - vector
  - z3
  - mtl
  - time
  - directory
  - process
  ghc-options: -Wall
  when:
    - condition: flag(solver-sat)
      dependencies:
      - toysolver ==0.7.0
      cpp-options: -DENABLE_SOLVER_SAT

flags:
  static:
    description: build statically linked binaries
    default: false
    manual: true

  gui:
    description: build playgui which requires OpenGL related libraries
    default: false
    manual: true

  bonusdeps:
    description: build bonusdeps which require GraphViz and graphviz packages
    default: false
    manual: true

  solver-sat:
    description: enable Solver.SAT module which requires toysolver package
    default: false
    manual: true  

executables:

  play-gui:
    main:                play-gui.hs
    source-dirs:         app-play
    other-modules:       []
    ghc-options:
    - -rtsopts
    - -threaded
    when:
      - condition: flag(gui)
        then:
          buildable: true
          dependencies:
          - icfpc2021
          - containers
          - process
          - GLFW-b
          - OpenGL
          - base
          - mtl
          - optparse-applicative
          - pretty
          - stm
          - transformers
          - random
        else:
          buildable: false
      - condition: flag(static)
        ghc-options: -static

  gui-helper:
    main:                gui-helper.hs
    other-modules:       []
    source-dirs:         app-play
    ghc-options:
    - -rtsopts
    - -threaded
    when:
      - condition: flag(gui)
        then:
          buildable: true
          dependencies:
          - icfpc2021
          - bytestring
          - containers
          - process
          - GLFW-b
          - OpenGL
          - base
          - mtl
          - optparse-applicative
          - pretty
          - StateVar
          - stm
          - transformers
          - text
        else:
          buildable: false
      - condition: flag(static)
        ghc-options: -static

  check:
    main:                check.hs
    source-dirs:         app-check
    ghc-options:
    - -rtsopts
    - -threaded
    dependencies:
    - icfpc2021
    - optparse-applicative
    - mtl
    - text

  submit:
    main:                submit.hs
    source-dirs:         app-submit
    ghc-options:
    - -rtsopts
    - -threaded
    dependencies:
    - http-client
    - http-conduit
    - optparse-applicative
    - mtl
    - text

  submit-gateway:
    main:                gateway.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -rtsopts
    - -threaded
    dependencies:
    - icfpc2021

  bonusdeps:
    main:                bonusdeps.hs
    source-dirs:         app-bonusdeps
    when:
      - condition: flag(bonusdeps)
        then:
          buildable: true
          dependencies:
          - icfpc2021
          - fgl
          - graphviz
        else:
          buildable: false

  solver-smt:
    main:                solver-smt.hs
    source-dirs:         app
    other-modules:       []
    dependencies:
      - icfpc2021

  z3help:
    main:                z3help.hs
    source-dirs:         app
    other-modules:       []
    dependencies:
    - z3

tests:
  icfpc2021-test:
    main:                spec.hs
    other-modules:
    - LibSpec
    - HoleSpec
    - ScoreSpec
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - fgl
    - icfpc2021
    - hspec
    - main-tester
    # - utf8-string
    # - unicode-show

  icfpc2021-doctest:
    main:                doctests.hs
    other-modules:       []
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2021
    - doctest
